server:
  port: 8081
  servlet:
    context-path: /api
spring:
#  application:
#    name: auth-server
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.MySQL8Dialect
      dialect: org.hibernate.dialect.H2Dialect
  datasource: 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysqldb:3306/test
#    username: root
#    password: root 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
#  cloud:
#    vault:
#      uri: http://localhost:8200
#      token: s.UjqiupZn26PIZJrAZAgZqso8
#      kv:
#        enabled: true
#        profile-separator: '/'